[package]
name = "kathleen-back"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lmdb-zero = "0.4.4"
dotenv = "0.15.0"
reductive = { version = "0.7", features = ["opq-train"] }